[package]
name = "cryptrack"
version = "0.1.0"
authors = ["Chris Foster <cfoster@greenviewdata.com>"]

[dependencies]
ctrlc = { version = "3.0", features = ["termination"] }
json = "0.11"
ws = { version = "0.7", features = ["ssl"] }
